### PR TITLE
Add Block Placement based on Distance 

### LINKED ISSUE #1: Add block by block placement option
Likely implemented by assigning a random delay to each block on explode for additional regeneration delay, configurable

### PR DESCRIPTION
**Pull request by rsammelson**
This adds a function to place blocks based on distance. Distance is measured using taxicab distance (xDistance + yDistance + zDistance). Blocks at distance 16 are placed after `regenDelay` minutes, while blocks closer or farther are adjusted by `distance * distanceDelay` seconds. This fixes #1.

### CODE REVIEW

**Comment by MicleBrick** [comment]
Have you tested this with tile entities like signs and such?

**Comment by rsammelson** [comment]
I haven’t, so I will, but as this does not modify the interaction with the object in any way, only with the entity/block exploding and the time that it exploded, it shouldn’t have any effect.

**Comment by rsammelson** [comment]
I just tested it with signs, and it works normally. They still have the previously existing bug that any text on them is wiped out.

**Comment by MicleBrick** [comment]
How long has that bug existed? Last time I tested it signs worked fine... Does it always happen or only in certain situations? Wall and standing or both?

**Comment by rsammelson** [comment]
It happens to standing and wall signs. The angle of standing signs is kept. It happened on the first version I tested, which was 2.5, and I don’t think that I made any modifications. See #11, it might be connected.

**Comment by MicleBrick** [comment]
I see. Thank you for all of this, I'll see if I can figure it out when my semester ends. I'll merge this now and test it/update the spigot page when I get a chance.

**Pull request merged**
